In [2]:
from tabula import read_pdf, convert_into

pdf_file="22972_Form 16_2021-22.pdf"
#list all tables
tables = read_pdf(pdf_file, pages='all',password='BCZPT7096P20111996')

# print(tables)
# tables.to_csv('pdfTOexcel.xlsx')

for table in tables:
    print(type(tables))
    print(tables)
    break
    #remove Nan columns
#     table = table.dropna(axis="columns")
#     table.to_csv(f'pdfTOcsv.csv')
#     if not table.empty:
#         print(f"Table {table_number}")
#         print(table)

#         convert the table dataframe into csv file
#         

#         table_number += 1
#

<class 'list'>
[                                         FORM NO. 16  \
0                                [See rule 31(1)(a)]
1                                             PART A
2  Certificate under Section 203 of the Income-ta...
3                             Certificate No.FHOLEEA
4                   Name and address of the Employer

                         Unnamed: 0
0                               NaN
1                               NaN
2                               NaN
3        Last updated on17-Jun-2021
4  Name and address of the Employee  ,                                  PAN of the Deductor  \
0                                                NaN
1                                          CIT (TDS)
2                                                NaN
3  Summary of amount paid/credited and tax deduct...
4                                         Quarter(s)
5                                                 Q1
6                                                 Q2
7                                                 Q3
8                                                 Q4
9                                        Total (Rs.)

                                 TAN of the Deductor  \
0                                         BLRT00417E
1                                    Assessment Year
2                                                NaN
3                                                NaN
4  Receipt Numbers of original\rquarterly stateme...
5                                           QUAVVLTD
6                                           QUDFCOWF
7                                           QUGRGGCD
8                                           QUJFAHDE
9                                                NaN

        PAN of the Employee  \
0                BCZPT7096P
1  Period with the Employer
2                       NaN
3                       NaN
4      Amount paid/credited
5                  79938.00
6                  79938.00
7                  79938.00
8                 104598.00
9                 344412.00

  Employee Reference No.\rprovided by the Employer\r(If available)  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                      Amount of tax deducted\r(Rs.)
5                                               0.00
6                                               0.00
7                                               0.00
8                                               0.00
9                                               0.00

                                  Unnamed: 0
0                                        NaN
1                                        NaN
2                            To\r31-Mar-2021
3                                        NaN
4  Amount of tax deposited / remitted\r(Rs.)
5                                       0.00
6                                       0.00
7                                       0.00
8                                       0.00
9                                       0.00  ,        Sl. No. Tax Deposited in respect of the\rdeductee\r(Rs.)  \
0          NaN                 Receipt Numbers of Form\rNo. 24G
1  Total (Rs.)                                              NaN

     Book Identification Number (BIN)                              Unnamed: 0  \
0  DDO serial number in Form no.\r24G  Date of transfer voucher\r(dd/mm/yyyy)
1                                 NaN                                     NaN

                              Unnamed: 1
0  Status of matching\rwith Form no. 24G
1                                    NaN  ,    Sl. No. Tax Deposited in respect of the\rdeductee\r(Rs.)  \
0      NaN                     BSR Code of the Bank\rBranch
1      1.0                                             0.00
2      2.0                                             0.00
3      3.0                                             0.00
4      4.0                                             0.00

         Challan Identification Number (CIN)             Unnamed: 0  \
0  Date on which Tax deposited\r(dd/mm/yyyy)  Challan Serial Number
1                                          -             05-05-2020
2                                          -             03-06-2020
3                                          -             03-07-2020
4                                          -             04-08-2020

                        Unnamed: 1 Unnamed: 2
0  Status of matching with\rOLTAS*        NaN
1                                -          F
2                                -          F
3                                -          F
4                                -          F  ,                                               Sl. No.  \
0                                                 NaN
1                                                   5
2                                                   6
3                                                   7
4                                                   8
5                                                   9
6                                                  10
7                                                  11
8                                                  12
9                                         Total (Rs.)
10                                       Verification
11  I,  KASARAGOD RAMADAS KAMATH, son / daughter o...
12                                              Place
13                                               Date
14                Designation: VICE PRESIDENT FINANCE

   Tax Deposited in respect of the\rdeductee\r(Rs.)  \
0                                               NaN
1                                              0.00
2                                              0.00
3                                              0.00
4                                              0.00
5                                              0.00
6                                              0.00
7                                              0.00
8                                              0.00
9                                              0.00
10                                              NaN
11                                              NaN
12                                        BANGALORE
13                                      19-Jun-2021
14               Full Name:KASARAGOD RAMADAS KAMATH

                  Challan Identification Number (CIN)  \
0                        BSR Code of the Bank\rBranch
1                                                   -
2                                                   -
3                                                   -
4                                                   -
5                                                   -
6                                                   -
7                                                   -
8                                                   -
9                                                 NaN
10                                                NaN
11                                                NaN
12  (Signature of person responsible for deduction...
13                                                NaN
14                                                NaN

                                   Unnamed: 0             Unnamed: 1  \
0   Date on which Tax deposited\r(dd/mm/yyyy)  Challan Serial Number
1                                  03-09-2020                      -
2                                  06-10-2020                      -
3                                  03-11-2020                      -
4                                  04-12-2020                      -
5                                  01-01-2021                      -
6                                  03-02-2021                      -
7                                  03-03-2021                      -
8                                  30-03-2021                      -
9                                         NaN                    NaN
10                                        NaN                    NaN
11                                        NaN                    NaN
12                                        NaN                    NaN
13                                        NaN                    NaN
14                                        NaN                    NaN

                         Unnamed: 2
0   Status of matching with\rOLTAS*
1                                 F
2                                 F
3                                 F
4                                 F
5                                 F
6                                 F
7                                 F
8                                 F
9                               NaN
10                              NaN
11                              NaN
12                              NaN
13                              NaN
14                              NaN  ,   Legend  Description                                         Definition
0      U    Unmatched  Deductors have not deposited taxes or have fur...
1      P  Provisional  Provisional tax credit is effected only for TD...
2      F        Final  In case of non-government deductors, payment d...
3      O   Overbooked  Payment details of TDS / TCS deposited in bank...,                                          FORM NO. 16  \
0                                             PART B
1  Certificate under Section 203 of the Income-ta...
2                             Certificate No.FHOLEEA
3                   Name and address of the Employer

                         Unnamed: 0
0                               NaN
1                               NaN
2        Last updated on17-Jun-2021
3  Name and address of the Employee  ,   PAN of the Deductor TAN of the Deductor       PAN of the Employee
0          BLRT00417E          BCZPT7096P                       NaN
1           CIT (TDS)     Assessment Year  Period with the Employer,    Details of Salary Paid and any other income and tax deducted  \
0              Whether opting for taxation u/s 115BAC
1                                                  1.
2                                                 (a)
3                                                 (b)
4                                                 (c)
5                                                 (d)
6                                                 (e)
7                                                  2.
8                                                 (a)
9                                                 (b)
10                                                (c)
11                                                (d)
12                                                (e)

                                           Unnamed: 0 Unnamed: 1 Unnamed: 2
0                                                  No        NaN        NaN
1                                        Gross Salary        Rs.        Rs.
2   Salary as per provisions contained in section ...  344412.00        NaN
3   Value of perquisites under section 17(2) (as p...       0.00        NaN
4   Profits in lieu of salary under section 17(3) ...       0.00        NaN
5                                               Total  344412.00        NaN
6   Reported total amount of salary received from ...        NaN       0.00
7   Less: Allowances to the extent exempt under se...        NaN        NaN
8   Travel concession or assistance under section ...       0.00        NaN
9   Death-cum-retirement gratuity under section 10...       0.00        NaN
10    Commuted value of pension under section 10(10A)       0.00        NaN
11  Cash equivalent of leave salary encashment und...       0.00        NaN
12         House rent allowance under section 10(13A)       0.00        NaN  ,    Unnamed: 0                                   A m o u n t  o f  a n y  \
0         (f)  [Note: Break-up to be filled and signed  by em...    NaN
1         NaN                provide at the bottom of this form]    NaN
2         (g)  Total amount of any other exemption under sect...    NaN
3         NaN  Total amount of exemption claimed under sectio...    NaN
4         (h)                                                NaN    NaN
5         NaN                    [2(a)+2(b)+2(c)+2(d)+2(e)+2(g)]    NaN
6         NaN  Total amount of salary received from current e...    NaN
7          3.                                                NaN    NaN
8         NaN                                        [1(d)-2(h)]    NaN
9          4.                  Less: Deductions under section 16    NaN
10        (a)            Standard deduction under section 16(ia)    NaN
11        (b)       Entertainment allowance under section 16(ii)    NaN
12        (c)            Tax on employment under section 16(iii)    NaN
13         5.  Total amount of deductions under section 16 [4...    NaN
14         6.  Income chargeable under the head "Salaries" [(...    NaN
15         7.  Add: Any other income reported by the employee...    NaN
16        NaN  Income (or admissible loss) from house propert...    NaN
17        (a)                                                NaN    NaN
18        NaN                           employee offered for TDS    NaN
19        (b)  Income under the head Other Sources offered fo...    NaN
20        NaN  Total amount of other income reported by the e...    NaN
21         8.                                                NaN    NaN
22        NaN                                        [7(a)+7(b)]    NaN
23         9.                           Gross total income (6+8)    NaN
24        10.                      Deductions under Chapter VI-A    NaN
25        NaN  Deduction in respect of life insurance premia,...    NaN
26        (a)                                                NaN    NaN
27        NaN              provident fund etc. under section 80C    NaN
28        NaN  Deduction in respect of contribution to certai...    NaN
29        (b)                                under section 80CCC    NaN
30        NaN  Deduction in respect of contribution by taxpay...    NaN
31        (c)                     scheme under section 80CCD (1)    NaN
32        (d)  Total deduction under section 80C, 80CCC and 8...    NaN
33        NaN  Deductions in respect of amount paid/deposited...    NaN
34        NaN            pension scheme under section 80CCD (1B)    NaN
35        (e)                                                NaN    NaN

    o t h e r  e x e m p t i o n  u n d e r  s e c t i o n  1 0    Unnamed: 1  \
0         NaN                NaN        NaN            NaN  NaN           NaN
1         NaN                NaN        NaN            NaN  NaN           NaN
2         NaN                NaN        NaN            NaN  NaN          0.00
3         NaN                NaN        NaN            NaN  NaN           NaN
4         NaN                NaN        NaN            NaN  NaN           NaN
5         NaN                NaN        NaN            NaN  NaN           NaN
6         NaN                NaN        NaN            NaN  NaN           NaN
7         NaN                NaN        NaN            NaN  NaN           NaN
8         NaN                NaN        NaN            NaN  NaN           NaN
9         NaN                NaN        NaN            NaN  NaN           NaN
10        NaN                NaN        NaN            NaN  NaN      50000.00
11        NaN                NaN        NaN            NaN  NaN          0.00
12        NaN                NaN        NaN            NaN  NaN       2500.00
13        NaN                NaN        NaN            NaN  NaN           NaN
14        NaN                NaN        NaN            NaN  NaN           NaN
15        NaN                NaN        NaN            NaN  NaN           NaN
16        NaN                NaN        NaN            NaN  NaN           NaN
17        NaN                NaN        NaN            NaN  NaN          0.00
18        NaN                NaN        NaN            NaN  NaN           NaN
19        NaN                NaN        NaN            NaN  NaN          0.00
20        NaN                NaN        NaN            NaN  NaN           NaN
21        NaN                NaN        NaN            NaN  NaN           NaN
22        NaN                NaN        NaN            NaN  NaN           NaN
23        NaN                NaN        NaN            NaN  NaN           NaN
24        NaN                NaN        NaN            NaN  NaN  Gross Amount
25        NaN                NaN        NaN            NaN  NaN           NaN
26        NaN                NaN        NaN            NaN  NaN      21840.00
27        NaN                NaN        NaN            NaN  NaN           NaN
28        NaN                NaN        NaN            NaN  NaN           NaN
29        NaN                NaN        NaN            NaN  NaN          0.00
30        NaN                NaN        NaN            NaN  NaN           NaN
31        NaN                NaN        NaN            NaN  NaN          0.00
32        NaN                NaN        NaN            NaN  NaN      21840.00
33        NaN                NaN        NaN            NaN  NaN           NaN
34        NaN                NaN        NaN            NaN  NaN           NaN
35        NaN                NaN        NaN            NaN  NaN          0.00

    Unnamed: 2         Unnamed: 3
0          NaN                NaN
1          NaN                NaN
2          NaN                NaN
3          NaN                NaN
4          NaN               0.00
5          NaN                NaN
6          NaN                NaN
7          NaN          344412.00
8          NaN                NaN
9          NaN                NaN
10         NaN                NaN
11         NaN                NaN
12         NaN                NaN
13         NaN           52500.00
14         NaN          291912.00
15         NaN                NaN
16         NaN                NaN
17         NaN                NaN
18         NaN                NaN
19         NaN                NaN
20         NaN                NaN
21         NaN               0.00
22         NaN                NaN
23         NaN          291912.00
24         NaN  Deductible Amount
25         NaN                NaN
26         NaN           21840.00
27         NaN                NaN
28         NaN                NaN
29         NaN               0.00
30         NaN                NaN
31         NaN               0.00
32         NaN           21840.00
33         NaN                NaN
34         NaN                NaN
35         NaN               0.00  ,                                                   (f)  \
0                                                 (g)
1                                                 (h)
2                                                 NaN
3                                                 (i)
4                                                 (j)
5                                                 (k)
6                                                 (l)
7                                                 11.
8                                                 12.
9                                                 13.
10                                                14.
11                                                15.
12                                                16.
13                                                17.
14                                                18.
15                                                19.
16                                       Verification
17  I,  KASARAGOD RAMADAS KAMATH, son/daughter of ...
18                                              Place
19                                               Date

   Deduction in respect of contribution by Employer to pension\rscheme under section 80CCD (2)  \
0   Deduction in respect of health insurance premi...